"""empty message

Revision ID: 0f5ff6357176
Revises: 45a6f7434657
Create Date: 2023-12-07 17:08:35.049953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5ff6357176'
down_revision = '45a6f7434657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index('idx_activity_date', ['activity_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_date')

    # ### end Alembic commands ###
