"""Initial migration

Revision ID: 835bcede8c74
Revises: 
Create Date: 2023-12-07 16:26:14.789802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835bcede8c74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_name', sa.String(length=255), nullable=True, server_default='test'))

    # Update existing rows with a non-null value
    op.execute("UPDATE activity SET activity_name = 'default_value' WHERE activity_name IS NULL")

    # Create an index on the activity_date column
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index('idx_activity_date', ['activity_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_date')
        batch_op.drop_column('activity_name')

    # ### end Alembic commands ###
